### ISSUE TITLE
Error when loading all the thumbnails (to be investigated)

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#207]
```
====> DEBUG |   1 | MainViewModel: Results changed. OnNext: Current alias: 'ps' | 
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.ComponentModel.TypeConverter.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\Images\Square44x44Logo.scale-100_contrast-black.png' (type 'String'); fallback value will be used, if available. BindingExpression:Path=Icon; DataItem='AliasQueryResult' (HashCode=9249362); target element is 'PackIconMaterial' (Name=''); target property is 'Kind' (type 'PackIconMaterialKind') FormatException:'System.FormatException: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\Images\Square44x44Logo.scale-100_contrast-black.png is not a valid value for PackIconMaterialKind.
 ---> System.ArgumentException: Requested value 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\Images\Square44x44Logo.scale-100_contrast-black.png' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.ComponentModel.TypeConverter.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value 'C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.206.863.0_x86__zpdnekdrzrea0\Assets\Square44x44Logo.scale-100.png' (type 'String'); fallback value will be used, if available. BindingExpression:Path=Icon; DataItem='AliasQueryResult' (HashCode=11000853); target element is 'PackIconMaterial' (Name=''); target property is 'Kind' (type 'PackIconMaterialKind') FormatException:'System.FormatException: C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.206.863.0_x86__zpdnekdrzrea0\Assets\Square44x44Logo.scale-100.png is not a valid value for PackIconMaterialKind.
 ---> System.ArgumentException: Requested value 'C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.206.863.0_x86__zpdnekdrzrea0\Assets\Square44x44Logo.scale-100.png' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.ComponentModel.TypeConverter.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '' (type 'String'); fallback value will be used, if available. BindingExpression:Path=Icon; DataItem='AliasQueryResult' (HashCode=31898818); target element is 'PackIconMaterial' (Name=''); target property is 'Kind' (type 'PackIconMaterialKind') FormatException:'System.FormatException:  is not a valid value for PackIconMaterialKind.
 ---> System.ArgumentException: Must specify valid information for parsing in the string. (Parameter 'value')
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
Exception thrown: 'System.FormatException' in System.ComponentModel.TypeConverter.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '' (type 'String'); fallback value will be used, if available. BindingExpression:Path=Icon; DataItem='AliasQueryResult' (HashCode=18653909); target element is 'PackIconMaterial' (Name=''); target property is 'Kind' (type 'PackIconMaterialKind') FormatException:'System.FormatException:  is not a valid value for PackIconMaterialKind.
 ---> System.ArgumentException: Must specify valid information for parsing in the string. (Parameter 'value')
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
====> TRACE |   1 | Fade in Storyboard completed... | 
====>  INFO |   1 | Window deactivated | 
====> TRACE |   1 | Fade out Storyboard completed... | 

```

**Comment by jibedoubleve** [comment]
In [Template.xaml](https://github.com/jibedoubleve/lanceur-bis/blob/3c7c08f4e1f751f80f9e3ca60f526a4f15d7e209/src/Lanceur/Xaml/Templates.xaml#L1-L2), we bind a `string` to a  `PackIconMaterial`. It should have a converter that return a default value instead of an error.
