### ISSUE TITLE
Cannot create macros

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#375]
# Description

Template `@macro@`  not working

# Logs
```
2023-11-06 08:54:57.2951;ERROR;Lanceur.Ui.UserNotification;1;Invalid URI: The format of the URI could not be determined.;"System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Lanceur.Infra.Managers.PackagedAppValidator.FixAsync(AliasQueryResult alias) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur.Infra\Managers\PackagedAppValidator.cs:line 51
   at Lanceur.Views.KeywordsViewModel.OnSaveOrUpdateAliasAsync(AliasQueryResult alias) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur\Views\KeywordsViewModel.cs:line 179"
```

**Comment by jibedoubleve** [comment]
Duplicate #377
