### ISSUE TITLE
Error when creating a macro keyword

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#377]
```
2023-11-06 08:54:37.3312;INFO;Lanceur.Infra.Managers.ExecutionManager;1;Executing alias 'add';
2023-11-06 08:54:37.3972;TRACE;ReactiveUI;1;DefaultViewLocator: Resolved service type 'ReactiveUI.IViewFor`1[[Lanceur.Views.KeywordsViewModel, Lanceur, Version=2.5.0.567, Culture=neutral, PublicKeyToken=null]]';
2023-11-06 08:54:37.3972;TRACE;Lanceur.Views.KeywordsView;1;Activating KeywordsView;
2023-11-06 08:54:37.4358;INFO;Lanceur.Views.MainView;1;Window deactivated;
2023-11-06 08:54:37.4358;DEBUG;ReactiveUI;1;MainViewModel: Query is empty, clearing the view. OnNext: '';
2023-11-06 08:54:37.4813;DEBUG;Lanceur.Views.SettingsViewModel;1;Request creation of alias 'fixthumb';
2023-11-06 08:54:37.4813;TRACE;Lanceur.Views.MainViewModel;1;Execution of 'add fixthumb' returned 0 result(s).;
2023-11-06 08:54:37.4813;DEBUG;ReactiveUI;1;MainViewModel: ViewModel is busy. OnNext: True;
2023-11-06 08:54:37.4813;DEBUG;ReactiveUI;1;MainViewModel: ViewModel is busy. OnNext: False;
2023-11-06 08:54:37.4813;DEBUG;ReactiveUI;1;MainViewModel: New results. OnNext: 0 element(s);
2023-11-06 08:54:37.4813;DEBUG;ReactiveUI;1;MainViewModel: Results changed. OnNext: Current alias: '<NULL>';
2023-11-06 08:54:37.4813;DEBUG;ReactiveUI;1;MainViewModel: Hiding control. OnNext: KeepAlive = False;
2023-11-06 08:54:37.6939;TRACE;Lanceur.Views.MainView;1;Fade out Storyboard completed...;
2023-11-06 08:54:57.2951;ERROR;Lanceur.Ui.UserNotification;1;Invalid URI: The format of the URI could not be determined.;"System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Lanceur.Infra.Managers.PackagedAppValidator.FixAsync(AliasQueryResult alias) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur.Infra\Managers\PackagedAppValidator.cs:line 51
   at Lanceur.Views.KeywordsViewModel.OnSaveOrUpdateAliasAsync(AliasQueryResult alias) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur\Views\KeywordsViewModel.cs:line 179"
```

**Comment by jibedoubleve** [comment]
Linked to #376
