### ISSUE TITLE
Error when launching an alias

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#403]
# What

An error occured when launching an alias

# Logs
```
2023-12-08 13:31:06.7527;DEBUG;ReactiveUI;1;MainViewModel: Command 'ExecuteAlias' or 'SearchAlias' triggered. OnNext: Current alias: 'r:og-bdd-tests-crosschannel';
2023-12-08 13:31:06.7527;DEBUG;ReactiveUI;1;MainViewModel: New results. OnNext: 6 element(s);
2023-12-08 13:31:06.7527;DEBUG;ReactiveUI;1;MainViewModel: Results changed. OnNext: Current alias: 'r:og-bdd-tests-crosschannel';
2023-12-08 13:31:08.0283;TRACE;Lanceur.Views.MainViewModel;1;Selecting next result. [Index: r:og-bdd-tests-xdl];
2023-12-08 13:31:08.0291;DEBUG;ReactiveUI;1;MainViewModel: Navigation occured OnNext: Current alias: 'r:og-bdd-tests-xdl' is INACTIVE;
2023-12-08 13:31:08.1431;DEBUG;ReactiveUI;16;MainViewModel: Query changed. OnNext: 'r:og-bdd-tests-xdl';
2023-12-08 13:31:08.2618;TRACE;Lanceur.Views.MainViewModel;1;Selecting next result. [Index: r:og-connect];
2023-12-08 13:31:08.2618;DEBUG;ReactiveUI;1;MainViewModel: Navigation occured OnNext: Current alias: 'r:og-connect' is INACTIVE;
2023-12-08 13:31:08.3640;DEBUG;ReactiveUI;16;MainViewModel: Query changed. OnNext: 'r:og-connect';
2023-12-08 13:31:08.4686;TRACE;Lanceur.Views.MainViewModel;1;Selecting next result. [Index: r:og-omnichannel-sync];
2023-12-08 13:31:08.4686;DEBUG;ReactiveUI;1;MainViewModel: Navigation occured OnNext: Current alias: 'r:og-omnichannel-sync' is INACTIVE;
2023-12-08 13:31:08.5766;DEBUG;ReactiveUI;16;MainViewModel: Query changed. OnNext: 'r:og-omnichannel-sync';
2023-12-08 13:31:08.8118;INFO;Lanceur.Infra.Managers.ExecutionManager;1;Executing alias 'r:og-omnichannel-sync';
2023-12-08 13:31:08.8393;TRACE;Lanceur.Infra.Managers.ExecutionManager;1;Executing process...;
2023-12-08 13:31:08.8393;DEBUG;Lanceur.Infra.Managers.ExecutionManager;1;Executing 'C:\Users\w129799\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\232.9921.83\bin\rider64.exe' with args ' C:\Projects\og-omnichannel-sync';
2023-12-08 13:31:08.8393;DEBUG;ReactiveUI;1;MainViewModel: ViewModel is busy. OnNext: True;
2023-12-08 13:31:08.8393;ERROR;Lanceur.Ui.UserNotification;1;Cannot execute alias 'r:og-omnichannel-sync: An error occurred trying to start process 'C:\Users\w129799\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\232.9921.83\bin\rider64.exe' with working directory 'C:\Windows\system32'. The system cannot find the file specified.';"System.ApplicationException: Cannot execute alias 'r:og-omnichannel-sync: An error occurred trying to start process 'C:\Users\w129799\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\232.9921.83\bin\rider64.exe' with working directory 'C:\Windows\system32'. The system cannot find the file specified.'
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\w129799\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\232.9921.83\bin\rider64.exe' with working directory 'C:\Windows\system32'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Lanceur.Infra.Managers.ExecutionManager.ExecuteProcess(AliasQueryResult query) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur.Infra\Managers\ExecutionManager.cs:line 109
   at Lanceur.Infra.Managers.ExecutionManager.ExecuteAliasAsync(AliasQueryResult query) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur.Infra\Managers\ExecutionManager.cs:line 79
   --- End of inner exception stack trace ---
   at Lanceur.Infra.Managers.ExecutionManager.ExecuteAliasAsync(AliasQueryResult query) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur.Infra\Managers\ExecutionManager.cs:line 82
   at Lanceur.Infra.Managers.ExecutionManager.ExecuteAsync(ExecutionRequest request) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur.Infra\Managers\ExecutionManager.cs:line 164
   at Lanceur.Views.MainViewModel.OnExecuteAliasAsync(AliasExecutionRequest request) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur\Views\MainViewModel.cs:line 267"
2023-12-08 13:31:08.8505;DEBUG;ReactiveUI;1;MainViewModel: ViewModel is busy. OnNext: False;
2023-12-08 13:31:11.7887;INFO;Lanceur.Views.MainView;1;Window deactivated;
2023-12-08 13:31:11.7887;DEBUG;ReactiveUI;1;MainViewModel: Query is empty, clearing the view. OnNext: '';
2023-12-08 13:31:12.0387;TRACE;Lanceur.Views.MainView;1;Fade out Storyboard completed...;
```

**Comment by jibedoubleve** [comment]
* The problem is due to Rider. 
* When updating the IDE, the path can change.
* After an update, starting the alias crashes because the path has changed and Lanceur cannot find the executable anymore

--> The only way to fix the issue is to add a comprehensive error message
