### ISSUE TITLE
Update path of Rider crashes

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur-bis#404]
# Logs
```
2023-12-19 14:58:59.7520;DEBUG;Lanceur.Infra.Managers.ExecutionManager;1;Executing 'C:\Projects\BACKUP_crosschannel.tester\Ingenico.ApiTester\bin\Debug\Ingenico.APITester.exe' with args '';
2023-12-19 14:58:59.7730;TRACE;Lanceur.Views.MainViewModel;1;Execution of 'api' returned 0 result(s).;
2023-12-19 14:58:59.7730;DEBUG;ReactiveUI;1;MainViewModel: ViewModel is busy. OnNext: True;
2023-12-19 14:58:59.7730;DEBUG;ReactiveUI;1;MainViewModel: ViewModel is busy. OnNext: False;
2023-12-19 14:58:59.7730;DEBUG;ReactiveUI;1;MainViewModel: New results. OnNext: 0 element(s);
2023-12-19 14:58:59.7730;DEBUG;ReactiveUI;1;MainViewModel: Results changed. OnNext: Current alias: '<NULL>';
2023-12-19 14:58:59.7730;DEBUG;ReactiveUI;1;MainViewModel: Hiding control. OnNext: KeepAlive = False;
2023-12-19 14:58:59.7730;DEBUG;ReactiveUI;1;MainViewModel: Query is empty, clearing the view. OnNext: '';
2023-12-19 14:58:59.9972;TRACE;Lanceur.Views.MainView;1;Fade out Storyboard completed...;
2023-12-19 14:59:00.0315;INFO;Lanceur.Views.MainView;1;Window deactivated;
2023-12-19 14:59:00.2637;TRACE;Lanceur.Views.MainView;1;Fade out Storyboard completed...;
2023-12-19 14:59:20.0036;INFO;Lanceur.Infra.SQLite.SQLiteRepository;1;Updating alias. (Id: 35);
2023-12-19 14:59:20.1185;DEBUG;ReactiveUI;1;KeywordsViewModel: Saved or updated alias. OnNext: Id: 35 - Name: apitester;
2023-12-19 14:59:20.1483;ERROR;Lanceur.Ui.UserNotification;1;BitmapMetadata is not available on BitmapImage. The unsupported member type is located on type 'System.Windows.Media.ImageMetadata'. Path: $.Thumbnail.Metadata.;"System.NotSupportedException: BitmapMetadata is not available on BitmapImage. The unsupported member type is located on type 'System.Windows.Media.ImageMetadata'. Path: $.Thumbnail.Metadata.
 ---> System.NotSupportedException: BitmapMetadata is not available on BitmapImage.
   at System.Windows.Media.Imaging.BitmapImage.get_Metadata()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteBytesUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at Lanceur.Views.KeywordsViewModel.UpdateAliasWithSynonyms(AliasQueryResult alias) in D:\a\lanceur-bis\lanceur-bis\src\Lanceur\Views\KeywordsViewModel.cs:line 296
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 104
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs:line 40
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 56
   at System.Reactive.SafeObserver`1.WrappingSafeObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Internal/SafeObserver.cs:line 40
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 96
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"
```

**Comment by jibedoubleve** [comment]
Cannot reproduce

**Comment by jibedoubleve** [comment]
Add some logging
